name: Python application

on:
  push:
    branches:
      - main
      - DEV
  pull_request:
    branches: 
      - main
      - DEV
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov radon mypy  # Added radon and mypy
        pip install -r API/requirements.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV


    - name: Test with pytest
      run: |
        pytest API/tests/ --cov=API


    - name: Display coverage report
      run: |
        coverage report
        coverage xml


    - name: Compute code metrics with radon
      run: radon cc . -a -nc


    - name: Type checking with mypy
      run: mypy API


    - name: Install newman for API testing
      run: npm install -g newman


    - name: Run API tests with newman
      run: newman run API/tests/Travelxptoday.postman_collection.json
